### ISSUE TITLE
being able to FILTER users with diferent attr

### ISSUE THREAD

**Issue by DanielKnourek** [panteLx/HASS-LDAP-Auth#1]
## Expected Behavior

When changing `ATTRS` variable, it should use this value for user filtering. 
Changing `ATTRS` variable from `cn` to `uid` would filter users based on `uid` and not `cn` (DisplayName)

## Actual Behavior

Variable `ATTRS` is unused. There is no way to search for users based on `uid`.

## Proposed Changes

Include variable `ATTRS` when formating `FILTER`

example
`FILTER = "(&{}({}={}))".format(BASE_FILTER, ATTRS, safe_username)`

https://github.com/panteLx/HASS-LDAP-Auth/blob/89a289b908bfe397a19fead8ca6fee7f0e58d2c9/auth.py#L50

**Comment by panteLx** [comment]
fixed, thank you!
